// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {downloader} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteVideo(arg1:string):Promise<void>;

export function Download(arg1:string):Promise<void>;

export function ExportHistory(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetDownloadHistory():Promise<Array<downloader.VideoInfo>>;

export function GetVideoList():Promise<Array<downloader.VideoInfo>>;

export function ImportHistory(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function RedownloadVideo(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SelectDownloadDirectory():Promise<string>;
