// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteVideo(arg1) {
  return window['go']['main']['App']['DeleteVideo'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function ExportHistory(arg1) {
  return window['go']['main']['App']['ExportHistory'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetVideoList() {
  return window['go']['main']['App']['GetVideoList']();
}

export function ImportHistory(arg1) {
  return window['go']['main']['App']['ImportHistory'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function RedownloadVideo(arg1) {
  return window['go']['main']['App']['RedownloadVideo'](arg1);
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function SelectDownloadDirectory() {
  return window['go']['main']['App']['SelectDownloadDirectory']();
}
